### PR TITLE
Use CMAKE_CXX_STANDARD

### PR DESCRIPTION
**Pull request by gadomski**
@hobu does this fix for you?

### CODE REVIEW

**Comment by hobu** [comment]
Can we use 17? PDAL moved to 17 at 2.4

**Comment by gadomski** [comment]
How badly do you need windoze? My desire to debug https://github.com/gadomski/fgt/actions/runs/4983553219/jobs/8920725582?pr=53 is low.

**Comment by hobu** [comment]
> How badly do you need windoze? 

not at all.

**Comment by hobu** [comment]
Does the same c++11 hardcode exist in CPD too?

**Comment by gadomski** [comment]
Probably, I did the cmake config at about the same time. I'll look.

**Comment by gadomski** [comment]
Nope, I did it "right" over there: https://github.com/gadomski/cpd/blob/ae413cf7456aeda04ffc371e41a52ca1a53dcd47/CMakeLists.txt#L5

**Comment by hobu** [comment]
bump that to 17 too though. Need `std::enable_if` support in eigen now.

**Comment by gadomski** [comment]
Tagged a new release here: https://github.com/gadomski/fgt/releases/tag/v0.4.10

**Pull request merged**
