### PR TITLE
0.4.8 readiness

### PR DESCRIPTION
**Pull request by hobu**
A few nits that were missed in the v0.4.7 tag.

### CODE REVIEW

**Comment by gadomski** [comment]
@hobu worrying that the errors weren't caught by https://github.com/gadomski/fgt/actions/runs/355952557, can you see why that was?

**Comment by hobu** [comment]
weird that actions didn't even run for this PR.

**Comment by gadomski** [comment]
@hobu #45 merged to master, please incorporate to this branch, re-push, and we can see if gh actions works this time.

**Comment by hobu** [comment]
I dont understand why the tests didn't trigger ...

**Comment by gadomski** [comment]
My guess is that https://github.com/gadomski/fgt/blob/4f5f38e6450829e01d131548204b73addb37f24f/.github/workflows/build.yml#L1-L2 only builds on pushes to **gadomski/fgt** pushes, not pull requests. Seems like we want `on: [push, pull_request]` per https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-a-list-of-events?

**Comment by gadomski** [comment]
Implemented in 9635659cccb2308222f547f74771814102015474, can you merge and re-push again and hopefully we'll be good to go?

**Comment by hobu** [comment]
Looks good. CPD will need similar CI tweaks too.

**Comment by gadomski** [comment]
Merged and tagged. I updated the github triggers in https://github.com/gadomski/cpd/commit/9a9f6a1062ba81bdb9968cb0a0e16be09e647b43 is there anything else needed for CPD that you know of?

**Comment by hobu** [comment]
> is there anything else needed for CPD that you know of?

Just the CPD version bump. With both of these libraries released, I'll start rolling the conda packages to staged-recipes. It's been taking them quite a while to merge and enable packages, so I'm not sure how long that will be.

**Pull request merged**
